# Site settings
title: Code pills
email: amico.andrea.90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just too lazy to use dropbox or GitHub to copy-paste code for everyday science scripts.
  Need to fit some cute data points? Need to analyze your favorite images?
  Need 20 lines of code to write a trash GUI you will use for a couple of weeks?
  If you want to steal something, feel free to copy-paste at your own risk, you will probably find a forest of bugs.

url: "http://andreaamico.github.io" # the base hostname & protocol for your site
github_username:  AndreaAmico

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: ""


kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false
