# Site settings
title: Code pills
email: amico.andrea.90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just too lazy to use Dropbox or GitHub for copying and pasting code for my everyday science scripts.
  Need to fit some cute data points? Want to analyze your favorite images?
  Looking for 20 lines of code to create a simple GUI you'll use for a couple of weeks?
  If you want to take something, feel free to copy and paste at your own risk—you’ll likely encounter a forest of bugs!

url: "http://andreaamico.github.io" # the base hostname & protocol for your site
github_username:  AndreaAmico

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: ""


kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false
