# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code pills
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just too lazy to use dropbox or github to copy paste code for everyday science scripts.
  Need to fit some cute data points? Need to analyse your favoutite images?
  Need 20 lines of code to write a trash gui you will use for a couple of weeks? 
  I hope not, infact i write it for me. If you want to steel something, feel free to copy-paste at your own risk,
  you will probably find a forest of bugs.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  AndreaAmico

# Build settings
markdown: kramdown
